version: "3.9"

volumes:
  postgres_data:
  mongo_data:

services:
  postgres:
    extends:
      file: ./postgres/docker-compose.yaml
      service: postgres
  pgadmin:
    extends:
      file: ./postgres/docker-compose.yaml
      service: pgadmin

  mongodb:
    extends:
      file: ./mongodb/docker-compose.yaml
      service: mongodb

  mongo-express:
    extends:
      file: ./mongodb/docker-compose.yaml
      service: mongo-express

  kafka-broker:
    extends:
      file: ./kafka/docker-compose.yaml
      service: broker

  # cloudbeaver:
  #   extends:
  #     file: ./dbeaver/docker-compose.yaml
  #     service: cloudbeaver
  #   networks:
  #     - backend
  # ✅ ADD THIS
  connect:
    extends:
      file: ./kafka/kafka-connect-docker-compose.yaml
      service: connect

  # control-center:
  #   extends:
  #     file: ./kafka/control-plane-docker-compose.yaml
  #     service: control-center
  #   networks:
  #     - backend
